POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "username": "to",
    "password": "test",
    "email": "test@example.com"
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username": "tdempster",
    "password": "test"
}

###

GET http://localhost:8080/api/auth/protect
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImlhdCI6MTU5NzU5NjUyNSwiZXhwIjoxNTk3NjgyOTI1fQ.QDAzhFke_j_wdV_PMiSNrlaUXHJsZmzr02ZxTQohitQ

###

POST http://localhost:8080/api/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTk4NzgwNDQ5LCJleHAiOjE1OTg4NjY4NDl9.8-1a1LvieSHc_PEp1eCRgks6E2XFqwsxDd7oN71AkD0
Content-Type: application/json

{
    "title": "A Title",
    "copy": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus culpa delectus eaque id incidunt neque nobis quam quis ullam vel."
}
